config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'credits/index'
  get 'credits' => 'credits#index'

  resources :people
  resources :groups
  resources :calendars
  resources :appointments
  resources :users
  get 'overview/index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'overview#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :credited_appointments, -> { forcredit }, class_name: "Appointment"

  default_scope { order('name ASC') }
  
  scope :actives, -> { where(active: true) }
  scope :inactives, -> { where(active: false) }
  
  validates :name, :group, :email, :phone, :user, presence: true
  validates_plausible_phone :phone
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authenticate_admin, only: [:destroy]

  # GET /people
  def index
    @people = Person.includes(:group)
    @sortedactives = @people.actives.sort_by do |person|
      person.name.split(" ").reverse.join.upcase
    end
    @sortedinactives = @people.inactives.sort_by do |person|
      person.name.split(" ").reverse.join.upcase
    end
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    authenticate_specific_user @person.user
  end

  # POST /people
  def create
    @person = Person.new(person_params)
    @person.user = current_user
    if @person.save
      redirect_to @person, flash: { success: 'Person was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    authenticate_specific_user @person.user
    if @person.update(person_params)
      redirect_to @person, flash: { success: 'Person was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, flash: { success: 'Person was successfully destroyed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :group_id, :email, :phone, :user_id, :active)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person, html: {class: 'form-horizontal'}) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation" class="alert alert-danger fade in">
      <p><%= pluralize(@person.errors.count, "error") %> prohibited this shifter from being saved:</p>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.text_field :name, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :group_id, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= collection_select(:person, :group_id, Group.all, :id, :name, {}, {class: 'form-control'}) %></div>
  </div>
  <div class="field form-group">
    <%= f.label :email, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.email_field :email, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label "Phone", {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.telephone_field :phone, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :active, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.check_box :active, class: 'form-control' %></div>
  </div>
  <% if admin? %>
    <div class="field form-group">
      <%= f.label "Associated account", {}, {class: 'col-sm-2 control-label'} %>
      <div class="col-sm-8"><%= collection_select(:person, :user_id, User.all, :id, :username, {}, {class: 'form-control'}) %></div>
    </div>
  <% end %>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h3>Editing <%= @person.name %></h3>

<%= render 'form' %>

<%= link_to 'Back to shifter', @person %>

app/views/people/index.html.erb
<h3>Active shifters</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @sortedactives.each do |person| %>
      <tr>
        <td><%= link_to person.name, person %></td>
        <td><%= link_to person.group.name, person.group %></td>
        <td><%= person.phone.phony_formatted(format: :international) %></td>
        <td><%= person.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Inactive shifters</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @sortedinactives.each do |person| %>
      <tr>
        <td><%= link_to person.name, person %></td>
        <td><%= link_to person.group.name, person.group %></td>
        <td><%= person.phone.phony_formatted(format: :international) %></td>
        <td><%= person.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shifter', new_person_path, class: "btn btn-primary" %>

app/views/people/new.html.erb
<h3>New shifter</h3>
<p>Here you can create a new shifter, for the purpose of assosciating that shifter with new or existing shift reservations.</p>

<p>Don't see the right group listed? Contact the shift coordinator to have a new group added.</p>

<%= render 'form' %>

<%= link_to 'Back to list of shifters', people_path %>

app/views/people/show.html.erb
<h3><%= @person.name %><% if not @person.active %> (Inactive)<% end %></h3>

<table class="table table-striped">
  <tr>
    <td>Email:</td>
    <td><%= @person.email %></td>
  </tr>
  
  <tr>
    <td>Phone:</td>
    <td><%= @person.phone.phony_formatted(format: :international) %></td>
  </tr>
  
  <tr>
    <td>Group:</td>
    <td><%= link_to @person.group.name, @person.group %></td>
  </tr>
  
  <% if admin? && @person.user %>
    <tr>
      <td>Associated account:</td>
      <td><%= link_to @person.user.username, user_path(@person.user) %></td>
    </tr>
  <% end %>
</table>

<% if @person.user == current_user || admin? %>
  <%= link_to 'Edit', edit_person_path(@person) %>
<% end %>
<% if admin? %>
| <%= link_to 'Delete', person_path(@person), method: :delete, data: { confirm: 'Are you sure? This will delete all appointments assosciated with this shifter.' } %>
<% end %>

<h3>Reservations</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Calendar</th>
      <th>Dates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person.appointments.order(:starts).each do |appointment| %>
      <tr>
        <td><%= link_to appointment.calendar.title, calendar_path(appointment.calendar) %></td>
        <td>
          <%= appointment.starts.strftime("%B %d, %Y") %>
          <% if appointment.starts != appointment.ends %>
            &ndash; <%= appointment.ends.strftime("%B %d, %Y") %>
          <% end %>
        </td>
        <td><%= link_to 'Details', appointment %></td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Edit', edit_appointment_path(appointment) %>
          <% end %>
        </td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Delete', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>