config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'credits/index'
  get 'credits' => 'credits#index'

  resources :people
  resources :groups
  resources :calendars
  resources :appointments
  resources :users
  get 'overview/index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'overview#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :people
  has_many :actives, -> { actives }, class_name: "Person"
  has_many :inactives, -> { inactives }, class_name: "Person"
  
  has_many :appointments, through: :people
  has_many :credited_appointments, through: :people
  
  default_scope { order('name ASC') }
  
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authenticate_admin, only: [:new, :edit, :create, :update, :destroy]

  # GET /groups
  def index
    @groups = Group.includes(:actives, :inactives)
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group, flash: { success: 'Group was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, flash: { success: 'Group was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    if @group.people.size == 0
      @group.destroy
      redirect_to groups_url, flash: { success: 'Group was successfully deleted.' }
    else
      redirect_to :back, flash: { "alert-danger": 'Group is not empty, so cannot be deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, html: {class: 'form-horizontal'}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger fade in">
      <p><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</p>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.text_field :name, class: 'form-control' %></div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h3>Editing <%= @group.name %></h3>

<%= render 'form' %>

<%= link_to 'Back to group', @group %>

app/views/groups/index.html.erb
<h3>All groups</h3>
  <% @groups.each do |group| %>
    <h4><%= link_to group.name, group %></h4>
    <% sortedactives = group.actives.sort_by do |person| %>
      <% person.name.split(" ").reverse.join.upcase %>
    <% end %>
    <%= sortedactives.map(&:name).to_sentence %>
    <% sortedinactives = group.inactives.sort_by do |person| %>
      <% person.name.split(" ").reverse.join.upcase %>
    <% end %>
    <% if sortedinactives.size > 0 %>
      <div style="color:gray;">(Former members: <%= sortedinactives.map(&:name).to_sentence %>)</div>
    <% end %>
  <% end %>
<br /><br />

<% if admin? %>
  <%= link_to 'New Group', new_group_path, class: "btn btn-primary" %>
<% end %>

app/views/groups/new.html.erb
<h3>New Group</h3>

<%= render 'form' %>

<%= link_to 'Back to list of groups', groups_path %>

app/views/groups/show.html.erb
<h3><%= @group.name %></h3>
<% if admin? %>
  <%= link_to 'Edit group name', edit_group_path(@group) %>
  | <%= link_to 'Delete group', group_path(@group), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h4>Group members</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% sortedpeople = @group.people.sort_by do |person| %>
      <% person.name.split(" ").reverse.join.upcase %>
    <% end %>
    <% sortedpeople.each do |person| %>
      <tr>
        <td><%= link_to person.name, person %><% if not person.active %> (inactive)<% end %></td>
        <td><%= person.email %></td>
        <td><%= person.phone.phony_formatted(format: :international) %></td>
        <td>
          <% if person.user == current_user || admin? %>
            <%= link_to 'Edit', edit_person_path(person) %>
          <% end %>
        </td>
        <td>
          <% if person.user == current_user || admin? %>
            <%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>Reservations</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Calendar</th>
      <th>Dates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% sortedappts = @group.appointments.sort_by do |appointment| %>
      <% appointment.starts %>
    <% end %>
    <% sortedappts.each do |appointment| %>
      <tr>
        <td><%= link_to appointment.person.name, person_path(appointment.person) %></td>
        <td><%= link_to appointment.calendar.title, calendar_path(appointment.calendar) %></td>
        <td>
          <%= appointment.starts.strftime("%B %d, %Y") %>
          <% if appointment.starts != appointment.ends %>
            &ndash; <%= appointment.ends.strftime("%B %d, %Y") %>
          <% end %>
        </td>
        <td><%= link_to 'Details', appointment %></td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Edit', edit_appointment_path(appointment) %>
          <% end %>
        </td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Delete', appointment_path(appointment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>