config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'credits/index'
  get 'credits' => 'credits#index'

  resources :people
  resources :groups
  resources :calendars
  resources :appointments
  resources :users
  get 'overview/index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'overview#index'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :appointments, dependent: :destroy
  has_many :appointments_today, -> { today }, class_name: "Appointment"
  has_many :appointments_tomorrow, -> { tomorrow }, class_name: "Appointment"
  has_many :appointments_upcoming, -> { upcoming }, class_name: "Appointment"
  
  default_scope { order('title ASC') }
  
  scope :actives, -> { where(active: true) }
  scope :inactives, -> { where(active: false) }
  
  validates :title, :description, :max_simultaneous, :days_per_credit, :start_time, :end_time, :min_days, :start_end_day, presence: true
  EMAILS_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  
  validate :watchers_valid
  def watchers_valid
    for watcher in watchers.split(/\s*,\s*/)
      if not watcher.match(EMAILS_REGEX)
        errors.add(:watchers, "is not a valid comma-separated list of email addresses")
        return
      end
    end
  end
  
  validates_inclusion_of :max_simultaneous, in: 0..99
  validates_inclusion_of :days_per_credit, in: 1..99
  validates_inclusion_of :min_days, in: 0..99
  validates_inclusion_of :start_end_day, in: -1..6
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authenticate_admin, only: [:new, :edit, :create, :update, :destroy]

  # GET /calendars
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1
  def show
    if (not params[:startmonth].nil?)
      begin
        theday = Date.parse(params[:startmonth] + "-01")
      rescue ArgumentError
        theday = Date.today
      end
    else
      theday = Date.today
    end
    @firstday = theday.beginning_of_week(:sunday)
    @startyear = theday.strftime("%Y")
    @startmonth = theday.strftime("%m")
    @months = params[:months].nil? ? 1 : params[:months].to_i
    @months = (@months > 0) ? @months : 1
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  def create
    @calendar = Calendar.new(calendar_params)
    if @calendar.save
      redirect_to @calendar, flash: { success: 'Calendar was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /calendars/1
  def update
    if @calendar.update(calendar_params)
      redirect_to @calendar, flash: { success: 'Calendar was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /calendars/1
  def destroy
    @calendar.destroy
    redirect_to calendars_url, flash: { success: 'Calendar was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:title, :description, :max_simultaneous, :days_per_credit, :min_days, :start_end_day, :start_time, :end_time, :no_credit_day, :active, :watchers)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar, html: {class: 'form-horizontal'}) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation" class="alert alert-danger fade in">
      <p><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</p>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.text_field :title, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :description, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.text_area :description, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label "Simultaneous reservations", {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.number_field :max_simultaneous, min: 1, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :days_per_credit, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.number_field :days_per_credit, min: 1, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label "Minimum days per reservation", {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.number_field :min_days, min: 1, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label "Start and end days", {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.select :start_end_day, [["No requirement", -1]].concat((0..6).map {|i| [Date::DAYNAMES[i], i]}), {}, {class: 'form-control'} %></div>
  </div>
  <div class="field form-group">
    <%= f.label :start_time, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.time_field :start_time, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :end_time, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.time_field :end_time, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :no_credit_day, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.check_box :no_credit_day, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :active, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.check_box :active, class: 'form-control' %></div>
  </div>
  <div class="field form-group">
    <%= f.label :watchers, {}, {class: 'col-sm-2 control-label'} %>
    <div class="col-sm-8"><%= f.text_area :watchers, class: 'form-control' %></div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h3>Editing calendar</h3>

<%= render 'form' %>

<%= link_to 'Back to calendar', @calendar %>

app/views/calendars/index.html.erb
<h3>Active calendars</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.actives.each do |calendar| %>
      <tr>
        <td><%= link_to calendar.title, calendar %></td>
        <td><%= calendar.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Inactive calendars</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.inactives.each do |calendar| %>
      <tr onclick="window.document.location='<%= calendar_url(calendar) %>'">
        <td><%= link_to calendar.title, calendar %></td>
        <td><%= calendar.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin? %>
  <%= link_to 'New Calendar', new_calendar_path, class: "btn btn-primary" %>
<% end %>

app/views/calendars/new.html.erb
<h3>New calendar</h3>

<%= render 'form' %>

<%= link_to 'See list of calendars', calendars_path %>

app/views/calendars/show.html.erb
<h3><%= @calendar.title %></h3>

<p>
  <%= @calendar.description %>
</p>

<ul>
  <% if @calendar.start_time.strftime("%H%M") != "0000" or @calendar.end_time.strftime("%H%M") != "0000" %>
    <li>
      Shifts start at <%= @calendar.start_time.strftime("%H:%M") %>
      <% if @calendar.start_time > @calendar.end_time %>
        on the day listed
      <% end %>
      and end at <%= @calendar.end_time.strftime("%H:%M") %>
      <% if @calendar.start_time > @calendar.end_time %>
        the next day
      <% end %>
      (LNGS local time)
    </li>
  <% end %>  
  <li>
    <% if @calendar.start_end_day? && @calendar.start_end_day > -1 %>
      Reservations must start and end on <%= Date::DAYNAMES[@calendar.start_end_day] %>
    <% else %>
      Reservations can be begin and end on any day of the week
    <% end %>
  </li>
  <li>Reservations must be at least <%= pluralize(@calendar.min_days, "day") %></li>
  <li>
    <% if @calendar.days_per_credit == 1 %>
      Each day earns 1 shift credit
    <% else %>
      Each day earns 1/<%= @calendar.days_per_credit %> of a shift credit
    <% end %>
    <% if @calendar.no_credit_day %>
      (one overlap day earns no credit)
    <% end %>
  </li>
  <li>
    <% if @calendar.max_simultaneous > 1 %>
      <%= pluralize(@calendar.max_simultaneous, "simultaneous reservation") %> permitted
    <% else %>
      Simultaneous reservations not permitted
    <% end %>
    <% if @calendar.no_credit_day %>
      (one overlap day allowed)
    <% end %>
  </li>
  <% if (@calendar.watchers.split(/\s*,\s*/)).to_sentence != "" %>
    <li>
      Notifications sent to <%= (@calendar.watchers.split(/\s*,\s*/)).to_sentence %>
    </li>
  <% end %>
</ul>

<% if admin? %>
  <p>
    <%= link_to 'Edit calendar details', edit_calendar_path(@calendar), class: "btn btn-primary" %>
    <%= link_to 'Delete calendar', calendar_path(@calendar), method: :delete, data: { confirm: 'You can just set this calendar to be inactive instead, and then it won\'t appear on the home page but will still keep the shift credits. Are you very sure you want to delete? This will permanently delete all reservations associated with this calendar and they will be removed from all shift credit calculations.' }, class: "btn btn-primary" %>
  </p>
<% end %>

<h3>Reservations</h3>
<div class="pull-left">
  <%= link_to "New Reservation", new_appointment_path({cal: @calendar.id}), class: "btn btn-primary" %>
</div>
<div class="pull-right">
  <form class="form-inline" style="padding-bottom:1em">
    <div class="field form-group">
      <%= number_field_tag :months, @months, min: 1, max: 36, size: 2, class: 'form-control' %>&nbsp;
      <label class="control-label" for="months">month(s)</label>
    </div>
    <div class="field form-group">
      <label class="control-label" for="startmonth">starting</label>&nbsp;
      <div class="input-group">
        <input value="" class="form-control datepicker" data-date-format="MMMM YYYY" type="text" name="startmonth" id="startmonth" />
        <span class="glyphicon glyphicon-calendar input-group-addon">
      </div>&nbsp;
    </div>
    <input type="submit" value="Show" class="btn btn-primary" />
    <a href="<%= request.path %>" class="btn btn-primary">Reset</a>
  </form>
</div>
<%= javascript_tag do %>
$(function () {
  $('#startmonth').datetimepicker({
    <% if not params[:startmonth].nil? %>
      defaultDate: '<%= j params[:startmonth] %>'
    <% else %>
      defaultDate: '<%= j Date.today.strftime("%Y-%m") %>'
    <% end %>
  });
});
<% end %>

<table class="table table-bordered table-striped">
  <tr>
    <th>Sunday</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
  </tr>
  <% sorted_appts = @calendar.appointments.includes(:person).sort_by{|appt| appt.starts} %>
  <% (0..(4.35*@months)).each do |week| %>
    <tr>
      <% (0..6).each do |day| %>
        <% thisday = @firstday + day + 7 * week %>
        <% day_appontments = sorted_appts.select { |appt| appt.starts <= thisday and appt.ends >= thisday } %>
        <td style="width: 14.29%<%= thisday == Date.today ? "; background-color: #B2DBA1" : "" %>" class="<%= day_appontments.length > 0 ? "success" : "" %>">
          <% if thisday.mday == 1 %>
            <% if @calendar.start_end_day > -1 and thisday.wday != @calendar.start_end_day %>
              <strong><%= thisday.strftime("%B %Y") %></strong>
            <% else %>
              <strong><%= link_to thisday.strftime("%B %Y"), new_appointment_path({cal: @calendar.id, startdate: thisday}) %></strong>
            <% end %>
          <% else %>
            <div class="pull-right">
              <% if @calendar.start_end_day > -1 and thisday.wday != @calendar.start_end_day %>
                <%= thisday.strftime("%-d") %>
              <% else %>
                <%= link_to thisday.strftime("%-d"), new_appointment_path({cal: @calendar.id, startdate: thisday}) %>
              <% end %>
              
            </div>
          <% end %>
          <% day_appontments.each do |appointment| %>
            <br /><%= link_to(appointment.person.name, appointment_path(appointment)) %>
          <% end %>          
        </td>  
      <% end %>
    </tr>
  <% end %>
</table>
<h3>Reservation list</h3>
<% if params[:future] == "no" %>
  Showing all reservations. <a href="<%= request.path %>?future=yes">See only current and future reservations</a>
  <% all_appointments = @calendar.appointments.includes(:person, :user).order(:starts) %>
<% else %>
  Showing all current and future reservations. <a href="<%= request.path %>?future=no">See all reservations</a>
  <% all_appointments = @calendar.appointments.includes(:person, :user).after(Date.today).order(:starts) %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Shifter</th>
      <th>Dates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% all_appointments.each do |appointment| %>
      <tr>
        <td><%= link_to appointment.person.name, person_path(appointment.person) %> (<%= link_to appointment.person.group.name, group_path(appointment.person.group) %>)</td>
        <td>
          <%= appointment.starts.strftime("%B %d, %Y") %>
          <% if appointment.starts != appointment.ends %>
            &ndash; <%= appointment.ends.strftime("%B %d, %Y") %>
          <% end %>
        </td>
        <td><%= link_to 'Details', appointment %></td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Edit', edit_appointment_path(appointment) %>
          <% end %>
        </td>
        <td>
          <% if appointment.user == current_user || appointment.person.user == current_user || admin? %>
            <%= link_to 'Delete', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>