config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'credits/index'
  get 'credits' => 'credits#index'

  resources :people
  resources :groups
  resources :calendars
  resources :appointments
  resources :users
  get 'overview/index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'overview#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shifter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_url %>">
          <img alt="Brand" src="<%= root_url %>site_logo.png" height=20px>
        </a>
        <a class="navbar-brand" href="<%= root_url %>">Shift Reservations</a>
        <ul class="nav navbar-nav">
          <li><%= link_to "Calendars", calendars_path %></li>
          <li><%= link_to "Shifters", people_path %></li>
          <li><%= link_to "Groups", groups_path %></li>
          <li><%= link_to "Shift Credits", credits_path, 'data-no-turbolink' => true %></li>
          <% if logged_in? %>
            <% if admin? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "All shifts", appointments_path %></li>
            <% end %>
            <li><%= link_to "My Account (" + current_user.username + ")", user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= flash_messages %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>